### ISSUE TITLE
Ubuntu requires libonig-dev package

### ISSUE THREAD

**Issue by nodanaonlyzuul** [moovweb/rubex#4]
Heyo.

I'm running Ubuntu 12.04 (64 bit) and needed to install the `libonig-dev` to install rubex.
I'm not sure if edge cases pop up with other versions of other distros but I had to run:

`sudo apt-get install libonig2 libonig-dev` 

So for at least a few cases the README probably needs to be updated.

Thanks for the great library.

**Comment by kalashnikov** [comment]
@nodanaonlyzuul Thanks for the hint!

**Comment by jveiga** [comment]
indeed, this tip helped me use the library ;)
