### ISSUE TITLE
go1 branch not visible

### ISSUE THREAD

**Issue by tinygrasshopper** [moovweb/rubex#5]
The go1 branch the documentation mentions is not found.

![screen shot 2015-02-09 at 1 41 54 pm](https://cloud.githubusercontent.com/assets/451613/6106426/92c3ca50-b061-11e4-9fa9-78abe4068200.png)

**Comment by twojtasz** [comment]
Sorry about that.  It has been put back.  Open another issue if it doesn't work please.
